(function() {var implementors = {};
implementors["vlive"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">IoError</a>&gt; for <a class=\"enum\" href=\"vlive/enum.Error.html\" title=\"enum vlive::Error\">Error</a>",synthetic:false,types:["vlive::error::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/serde_json/1.0.9/serde_json/error/struct.Error.html\" title=\"struct serde_json::error::Error\">JsonError</a>&gt; for <a class=\"enum\" href=\"vlive/enum.Error.html\" title=\"enum vlive::Error\">Error</a>",synthetic:false,types:["vlive::error::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://docs.rs/hyper/0.11.16/hyper/error/enum.Error.html\" title=\"enum hyper::error::Error\">HyperError</a>&gt; for <a class=\"enum\" href=\"vlive/enum.Error.html\" title=\"enum vlive::Error\">Error</a>",synthetic:false,types:["vlive::error::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/hyper/0.11.16/hyper/uri/struct.UriError.html\" title=\"struct hyper::uri::UriError\">UriError</a>&gt; for <a class=\"enum\" href=\"vlive/enum.Error.html\" title=\"enum vlive::Error\">Error</a>",synthetic:false,types:["vlive::error::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/reqwest/0.8.5/reqwest/error/struct.Error.html\" title=\"struct reqwest::error::Error\">ReqwestError</a>&gt; for <a class=\"enum\" href=\"vlive/enum.Error.html\" title=\"enum vlive::Error\">Error</a>",synthetic:false,types:["vlive::error::Error"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"enum\" href=\"vlive/enum.Error.html\" title=\"enum vlive::Error\">Error</a>",synthetic:false,types:["vlive::error::Error"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
