name: CI

on:
    push:
    pull_request:
    schedule:
        # To ensure new videos deserialize properly
        # Daily at 01:15
        - cron: "15 1 * * *"

jobs:
    build:
        continue-on-error: ${{ matrix.toolchain != 'stable' }}
        strategy:
            matrix:
                toolchain:
                    - stable
                    - beta
                    - nightly
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Select toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.toolchain }}
                  override: true

            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Build vlive-rs
              uses: actions-rs/cargo@v1
              with:
                  command: build

            - name: Test vlive-rs
              uses: actions-rs/cargo@v1
              with:
                  command: test
